### ISSUE TITLE
"Related Questions" section inverted colours

### ISSUE THREAD

**Issue by altern8tif** [StylishThemes/Quora-Dark#12]
The colours for the "Related Questions" section should be inverted (ie. white text on dark background).

![screen shot 2017-03-01 at 8 45 18 am](https://cloud.githubusercontent.com/assets/5793364/23441161/7f3325ae-fe5b-11e6-979b-e63b035a96dc.png)

**Comment by AbdelrahmanHafez** [comment]
+1

**Comment by Mottie** [comment]
Hi @altern8tif & @AbdelrahmanHafez!

Sorry for not responding earlier. I forgot about this issue after returning from my trip. I don't think anyone else could have fixed it since the pane is not that easy to find. It would have helped if a link to the page was also included.

Anyway, it should be all fixed now.
